Repository kosa3-OverClock/MoveToMove_MOM_BE, pull requests merged in 2024-09, with the labels that each got.

#29 Feat: actuator 추가 및 프론트와 웹소켓 연동 코드
  build.gradle
  src/main/java/com/kosa/kosafinalprojbackend/domains/chat/WebSocketController.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/chat/model/WebSocketMessage.java
  src/main/java/com/kosa/kosafinalprojbackend/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/kosa/kosafinalprojbackend/global/websocket/WebSocketConfig.java
Labels: enhancement

#33 Feat: 코멘트 수정 기능 추가
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/controller/CardController.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/service/CardService.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/comment/controller/CommentController.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/comment/domian/form/CommentForm.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/comment/service/CommentService.java
  src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
  src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/comment/CommentMapper.java
  src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/kanbancard/KanbanCardMapper.java
  src/main/resources/mybatis/mappers/comment-mapper.xml
Labels: enhancement

#34 Feat: 코멘트 삭제 기능 추가
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/comment/controller/CommentController.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/comment/service/CommentService.java
  src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
  src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/comment/CommentMapper.java
  src/main/resources/mybatis/mappers/comment-mapper.xml
Labels: enhancement

#35 Modify: 칸반 카드 위치 이동 수정, 칸반 상세 조회 수정
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/domain/dto/CardCommentDto.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/domain/dto/CardDetailDto.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/service/CardService.java
  src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/kanbancard/KanbanCardMapper.java
  src/main/resources/mybatis/mappers/kanbancard-mapper.xml
Labels: modify

#36 Feat: 칸반보드 컬럼 순서 변경 구현 , 칸반 보드 컬럼 삭제 시 로직 수정
  .gitignore
  build.gradle
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/controller/ColumnController.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/model/dto/ColumnDto.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/model/form/KanbanColumnMoveRequest.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/service/ColumnService.java
  src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
  src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/kanbancolumn/KanbanColumnMapper.java
  src/main/resources/mybatis/mappers/kanbancolumn-mapper.xml
Labels: enhancement, modify

#37 Feat: 사용자 정보 조회
  src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/MemberController.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/MemberService.java
Labels: enhancement

#39 Modify: 회원정보 수정 기능 수정
  src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/MemberService.java
  src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
  src/main/java/com/kosa/kosafinalprojbackend/global/error/exception/CustomBaseException.java
  src/main/java/com/kosa/kosafinalprojbackend/global/error/exception/GlobalExceptionHandler.java
  src/main/java/com/kosa/kosafinalprojbackend/global/error/exception/InternalServerException.java
  src/main/java/com/kosa/kosafinalprojbackend/global/error/exception/JwtValidationException.java
  src/main/java/com/kosa/kosafinalprojbackend/global/error/exception/NotFoundException.java
  src/main/java/com/kosa/kosafinalprojbackend/global/error/response/ErrorResponse.java
  src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/member/MemberMapper.java
  src/main/resources/mybatis/mappers/member-mapper.xml
Labels: modify

#40 Modify: 닉네임 중복 확인 수정
  src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/MemberService.java
Labels: modify

#44 Feat/bjw/columns 컬럼 컨트롤러 위치 수정
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/controller/ColumnController.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/model/form/KanbanColumnMoveRequestForm.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/service/ColumnService.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/controller/ProjectController.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/CustomLogoutSuccessHandler.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/member/oAuth/handler/CustomOAuth2AuthenticationFailureHandler.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/member/oAuth/handler/CustomOAuth2AuthenticationSuccessHandler.java
  src/main/java/com/kosa/kosafinalprojbackend/global/security/filter/JwtTokenProvider.java
Labels: modify

#45 Modify: 회원탈퇴 기능 수정
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/comment/controller/CommentController.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/controller/ProjectController.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/MemberController.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/MemberService.java
  src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
  src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/member/MemberMapper.java
  src/main/resources/mybatis/mappers/kanbancolumn-mapper.xml
  src/main/resources/mybatis/mappers/member-mapper.xml
Labels: modify

#46 Modify: 프로젝트 저장 로직 수정
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/controller/ColumnController.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/service/ProjectService.java
  src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/kanbancolumn/KanbanColumnMapper.java
  src/main/resources/mybatis/mappers/kanbancolumn-mapper.xml
Labels: modify

#49 Modify: 토큰 관련 수정
  src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/CustomLogoutHandler.java
  src/main/java/com/kosa/kosafinalprojbackend/global/security/filter/JwtAuthenticationFilter.java
Labels: modify

#50 Modify: 3차 main merge
  src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/CustomLogoutHandler.java
  src/main/java/com/kosa/kosafinalprojbackend/global/security/filter/JwtAuthenticationFilter.java
Labels: modify

#53 Feat: 폴더 조회 기능 구현
  src/main/java/com/kosa/kosafinalprojbackend/domains/folder/controller/FolderController.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/folder/model/dto/FolderSubFolderProjectDto.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/folder/model/dto/NotIncludedProjectDto.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/folder/service/FolderService.java
  src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/folder/FolderMapper.java
  src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/projectjoin/ProjectJoinMapper.java
  src/main/resources/mybatis/mappers/folder-mapper.xml
  src/main/resources/mybatis/mappers/project-join-mapper.xml
Labels: enhancement, modify

#57 Modify: Comment Dto 수정
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/domain/dto/CardCommentDto.java
Labels: modify

#61 Modify: 프로젝트 기준 칸반 카드 상세 수정
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/controller/ProjectController.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/model/dto/ProjectCardDetailDto.java
  src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/service/ProjectService.java
Labels: modify

#93 Modify: 칸반 카드 수정 시 웹소켓 메시지
  src/main/java/com/kosa/kosafinalprojbackend/global/websocket/controller/WebSocketController.java
Labels: modify
